name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Touka-Agra   # Your GitHub username (case-sensitive)
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push SVG
        run: |
            git config --local user.name "${GITHUB_ACTOR}"
            git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            if [ -f dist/github-contribution-grid-snake.svg ]; then
              git add dist/
              git commit -m "Update GitHub Snake contribution" || echo "No changes to commit"
              git push origin HEAD
            else
              echo "SVG not generated, skipping commit"
            fi
