name: GitHub Snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v1.2.0
        with:
          github_user_name: Touka-Agra
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Commit & push changes
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if [ -f dist/github-contribution-grid-snake.svg ]; then
            git add dist/
            git commit -m "Update GitHub Snake contribution" || echo "No changes to commit"
            git push origin HEAD
          else
            echo "SVG not generated, skipping commit"
